export {HomePage} from "./HomePage/HomePage";
export {ProfilePage} from "./ProfilePage/ProfilePage";
export {CountriesPage} from "./CountriesPage/CountriesPage";
export {AboutPage} from "./AboutPage/AboutPage";
export {SoatoPage} from "./SoatoPage/SoatoPage";
export {SooguPage} from "./SooguPage/SooguPage";
export {KfsPage} from "./KfsPage/KfsPage";
export {KopfPage} from "./KopfPage/KopfPage";
export {CsdpPage} from "./CsdpPage/CsdpPage";
